apiVersion: v1
kind: Service
metadata:
  name: codeserver-svc
spec:
  selector:
    app: codeserver
  ports:
  - protocol: TCP
    port: 8443
    targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeserver
  labels:
    app: codeserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeserver
  template:
    metadata:
      labels:
        app: codeserver
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      containers:
        - name: codeserver
          image: lscr.io/linuxserver/code-server:4.6.1
          imagePullPolicy: "IfNotPresent"
          readinessProbe:
            httpGet:
              path: /
              port: 8443
              scheme: HTTP
          volumeMounts:
            - mountPath: /usr/src/app
              name: git-vol
              subPath: app
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: Asia/Seoul
            - name: DEFAULT_WORKSPACE
              value: /usr/src/app
      volumes:
      - name: git-vol
        persistentVolumeClaim:
          claimName: git-vol
---
