version: '3.5'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 9443:9443
    environment:
      - LT_FRONTEND_LANGUAGE_TARGET=ko
      - LT_HOST=0.0.0.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
volumes:
  portainer_data:
