apiVersion: v1
kind: Service
metadata:
  name: pgadmin4-svc
  labels:
    package: pgadmin4
spec:
  selector:
    package: pgadmin4
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin4
  labels:
    package: pgadmin4
spec:
  replicas: 1
  selector:
    matchLabels:
      package: pgadmin4
  template:
    metadata:
      labels:
        package: pgadmin4
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 20
      containers:
        - name: pgadmin4
          image: dpage/pgadmin4
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /var/lib/pgadmin
              name: pgadmin4-data
          envFrom:
            - configMapRef:
                name: pgadmin4-config
      volumes:
      - name: pgadmin4-data
        persistentVolumeClaim:
          claimName: pgadmin4-data
          