apiVersion: v1
kind: Service
metadata:
  name: noj-judge-server-svc
  labels:
    package: noj
    app: noj-judge-server
spec:
  selector:
    app: noj-judge-server
    package: noj
  type: ClusterIP
  ports:
  - name: http
    port: 2358
    targetPort: 2358
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: noj-judge-server
  labels:
    app: noj-judge-server
    package: noj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noj-judge-server
  template:
    metadata:
      labels:
        app: noj-judge-server
        package: noj
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 20
      containers:
        - name: noj-judge-server
          image: njuptaaa/judge_server
          imagePullPolicy: "IfNotPresent"
          securityContext:
            capabilities:
              drop:
                - KILL
                - SETPCAP
                - MKNOD
                - NET_BIND_SERVICE
                - SYS_CHROOT
                - SETFCAP
                - FSETID
          command: ["/bin/sh", "-c"]
          args: 
            - |
              cd /
              ln -s /app/log log
              ln -s /app/tests/test_case test_case
              ln -s /app/run judger
              sleep 5000
          envFrom:
            - configMapRef:
                name: noj-judge-server-config
          volumeMounts:
            - name: git-vol
              mountPath: /app
              subPath: app
      volumes:
        - name: git-vol
          persistentVolumeClaim:
            claimName: git-vol
          